"""TechNova_SpamDetection50kOptimized.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fkUo-t6NKfPPXFFIRKvi5Hj44fdJTHbG

# **TechNova - Spam Detection (AI Model Training)**

## **COS30049 - Computing Technology Innovation Project**

---

### **Project Overview**
This notebook presents a comprehensive Machine Learning pipeline for **Spam Detection** - classifying text messages/emails as either **Spam** or **Ham** (not spam).

The pipeline includes:
1. **Data Loading & Exploration** - Understanding the dataset distribution and characteristics
2. **Data Preprocessing** - Text cleaning, normalization, and feature engineering
3. **Feature Extraction** - TF-IDF Vectorization
4. **Model Training** - Naive Bayes, SVM, Logistic Regression, Random Forest
5. **Model Evaluation** - Accuracy, Precision, Recall, F1-Score, Confusion Matrix, ROC Curve
6. **Cross-Validation** - 5-Fold CV for robust performance estimation
7. **Hyperparameter Tuning** - GridSearchCV for optimal model configuration
8. **Model Saving** - Exporting the best model and vectorizer with joblib
9. **Prediction Interface** - Function to classify new text inputs

---
## **Step 1: Setup & Import Libraries**

We use the following libraries:
- **pandas** - data manipulation and analysis
- **numpy** - numerical operations
- **matplotlib & seaborn** - data visualization
- **scikit-learn** - ML models, preprocessing, evaluation
- **nltk** - natural language processing (stopwords, tokenization)
- **wordcloud** - word cloud visualization
- **joblib** - model serialization
"""

# Install required packages
# pip install pandas numpy matplotlib seaborn scikit-learn nltk wordcloud joblib

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import re
import string
import warnings
warnings.filterwarnings("ignore")


# NLP
import nltk
nltk.download("stopwords", quiet=True)
nltk.download("punkt", quiet=True)
nltk.download("punkt_tab", quiet=True)
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

# Scikit-learn
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV, StratifiedKFold
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC, SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    confusion_matrix, classification_report, roc_curve, auc
)
from sklearn.calibration import CalibratedClassifierCV

# Visualization
# from wordcloud import WordCloud

# Model saving
import joblib

# Set plot style (disabled for pure execution)
# sns.set_theme(style="whitegrid")
# plt.rcParams["figure.figsize"] = (10, 6)
# plt.rcParams["font.size"] = 12

print("All libraries imported successfully!")

"""### **1.1 Upload & Load Dataset**

Upload your CSV dataset file. The dataset should contain text messages/emails with their corresponding labels (spam/ham).

"""

# Let user upload/select file using tkinter (Local equivalent of google.colab files.upload)
import tkinter as tk
from tkinter import filedialog
import sys

print("Please select your dataset file (.csv) in the popup window...")
root = tk.Tk()
root.withdraw()  # Hide the main window
root.attributes('-topmost', True)  # Bring to front

target_file = filedialog.askopenfilename(
    title="Upload/Select Training Dataset",
    filetypes=(("CSV files", "*.csv"), ("All files", "*.*"))
)

if not target_file:
    print("No file selected! Exiting...")
    sys.exit()

print(f"\nUploaded file (selected): {os.path.basename(target_file)}")
print("--- Loading Data ---")

if not os.path.exists(target_file):
    raise ValueError(f"File {target_file} not found in the current directory.")

try:
    try:
        df = pd.read_csv(target_file)
    except UnicodeDecodeError:
        print(f"  'utf-8' decoding failed for {target_file}. Trying 'latin1'...")
        df = pd.read_csv(target_file, encoding='latin1')
    
    print(f"Loaded {target_file}: {df.shape}")
except Exception as e:
    raise ValueError(f"Error loading {target_file}: {e}")

print(f"\nTotal shape after loading: {df.shape}")

# --- Optimize RAM & Data Integrity ---
# Drop unneeded 'Unnamed' columns and 'Message ID' to save memory
cols_to_drop = [col for col in df.columns if col.startswith('Unnamed') or col in ['Message ID', 'Date']]
df.drop(columns=cols_to_drop, inplace=True, errors='ignore')

# Pre-fill NaNs to avoid TypeError like 'float has no len()' during EDA
df['Subject'] = df['Subject'].fillna('')
df['Message'] = df['Message'].fillna('')

# 2. Exploratory Data Analysis (EDA)

# 2.1 Basic Data Information

# Display first few rows
print("=" * 60)
print("FIRST 5 ROWS")
print("=" * 60)
df.head()

# Dataset info
print("=" * 60)
print("DATASET INFO")
print("=" * 60)
print(f"Shape: {df.shape}")
print(f"\nColumns: {list(df.columns)}")
print(f"\nData Types:")
print(df.dtypes)
print(f"\nMissing Values:")
print(df.isnull().sum())
print(f"\nDuplicate Rows: {df.duplicated().sum()}")

# Statistical summary
print("=" * 60)
print("STATISTICAL SUMMARY")
print("=" * 60)
df.describe(include="all")

# 2.2 Target Distribution

# Identify the label column
# Adjust this if your dataset uses a different column name
df['combined_text'] = df['Subject'].astype(str) + " " + df['Message'].astype(str)
text_col = "combined_text"
label_col = "Spam/Ham"

print(f"Label column: \"{label_col}\"")
print(f"Text column: \"{text_col}\"")
print(f"\nClass distribution:")
print(df[label_col].value_counts())
print(f"\nClass proportions:")
print(df[label_col].value_counts(normalize=True).round(4) * 100)

# 2.3 Word Cloud Visualization

# Word Cloud generation disabled for pure execution script
print("\nWord Cloud visualization skipped.")

"""---
## **Step 3: Data Preprocessing**

Preprocessing is crucial for NLP tasks. We will:
1. Remove duplicates and handle missing values
2. Clean text: lowercase, remove punctuation, remove stopwords
3. Encode labels (spam \u2192 1, ham \u2192 0)
4. Split data into train/test sets

### **3.1 Data Cleaning**
"""

# Remove duplicates
df['combined_text'] = df['Subject'].astype(str) + " " + df['Message'].astype(str)
text_col = "combined_text"
df = df[df[text_col].str.strip() != ""]
df.drop_duplicates(inplace=True)
print(f"Shape after removing empty messages and duplicates: {df.shape}")

# 3.2 Text Preprocessing

# Text cleaning function
stop_words = set(stopwords.words("english"))

def clean_text(text):
    """
    Clean and preprocess text:
    1. Convert to lowercase
    2. Remove URLs
    3. Remove email addresses
    4. Remove numbers
    5. Remove punctuation
    6. Remove stopwords
    7. Remove extra whitespace
    """
    text = str(text).lower()
    text = re.sub(r"http\S+|www\S+|https\S+", "url_placeholder", text)
    text = re.sub(r"\S+@\S+", "email_placeholder", text)
    text = re.sub(r"\d+", "number_placeholder", text)
    
    # Keep important punctuation like !, ?, $, €, £ instead of removing all
    # text = text.translate(str.maketrans("", "", string.punctuation))
    text = re.sub(r'[^\w\s!$?\-€£]', '', text)
    
    tokens = word_tokenize(text)
    tokens = [w for w in tokens if w not in stop_words and len(w) > 1]
    return " ".join(tokens)

# Apply cleaning
print("Cleaning text data...")
df["cleaned_text"] = df[text_col].apply(clean_text)

# Show before vs after
print("\n--- Before vs After Cleaning ---")
for i in range(3):
    print(f"\nOriginal:  {df[text_col].iloc[i][:100]}...")
    print(f"Cleaned:   {df['cleaned_text'].iloc[i][:100]}...")
print("\nText cleaning complete!")

# 3.3 Label Encoding

# Filter for only 'ham' and 'spam' labels to remove noise
df[label_col] = df[label_col].astype(str).str.lower().str.strip()
df = df[df[label_col].isin(['ham', 'spam'])]

# Encode labels: ham → 0, spam → 1
le = LabelEncoder()
df["label"] = le.fit_transform(df[label_col])

print("Label Encoding Mapping:")
for cls, encoded in zip(le.classes_, le.transform(le.classes_)):
    print(f"  {cls} → {encoded}")

print(f"\nEncoded distribution:")
print(df["label"].value_counts())

"""### **3.4 Feature Extraction \u2014 TF-IDF Vectorization**

TF-IDF (Term Frequency \u2014 Inverse Document Frequency) converts text into numerical feature vectors.
- **TF**: How often a word appears in a document
- **IDF**: Penalizes words that appear in many documents (common words)

"""

"""### **3.4 & 3.5 Train/Test Split (Before TF-IDF to avoid Leakage)**

"""
from sklearn.model_selection import train_test_split

# NOTE: We split the raw text FIRST, before vectorization
X_raw = df["cleaned_text"]
y = df["label"]

X_train, X_temp, y_train, y_temp = train_test_split(X_raw, y, test_size=0.3, random_state=42, stratify=y)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42, stratify=y_temp)

print(f"Total sets: {X_raw.shape[0]}")
print(f"---")
print(f"Training set:   {X_train.shape[0]} samples (70%)")
print(f"Validation set: {X_val.shape[0]} samples (15%)")
print(f"Testing set:    {X_test.shape[0]} samples (15%)")

print(f"\nLabel distributition in Validation set:")
print(y_val.value_counts(normalize=True))

"""---
## **Step 4: Model Training & Evaluation**

We will train and compare **4 different classification algorithms**:
1. **Multinomial Naive Bayes** \u2014 Fast, works well with text data
2. **Support Vector Machine (SVM)** \u2014 Effective in high-dimensional spaces
3. **Logistic Regression** \u2014 Simple yet powerful linear classifier
4. **Random Forest** \u2014 Ensemble method, robust to overfitting

### **4.1 Define Models**
"""

from sklearn.pipeline import Pipeline

def get_tfidf():
    """Returns a fresh instance of TfidfVectorizer to avoid state sharing"""
    return TfidfVectorizer(max_features=10000, stop_words="english",
                           ngram_range=(1, 2), min_df=5, max_df=0.8)

# Define models inside a Pipeline to prevent Data Leakage, using fresh vectorizer for each
models = {
    "Naive Bayes": Pipeline([("tfidf", get_tfidf()), ("clf", MultinomialNB())]),
    "SVM (LinearSVC)": Pipeline([("tfidf", get_tfidf()), ("clf", CalibratedClassifierCV(LinearSVC(random_state=42, max_iter=10000)))]),
    "Logistic Regression": Pipeline([("tfidf", get_tfidf()), ("clf", LogisticRegression(random_state=42, max_iter=1000))]),
    "Random Forest": Pipeline([("tfidf", get_tfidf()), ("clf", RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1))])
}

print(f"Models to train: {list(models.keys())}")

# 4.2 Train & Evaluate All Models

# Train and evaluate each model
results = {}

print("=" * 70)
print("MODEL TRAINING & EVALUATION")
print("=" * 70)

for name, model in models.items():
    print(f"\n{'\u2500' * 50}")
    print(f"Training: {name}")
    print(f"{'\u2500' * 50}")

    # Train
    model.fit(X_train, y_train)

    # Predict on Train, Val, Test to track overfitting
    y_train_pred = model.predict(X_train)
    y_val_pred = model.predict(X_val)
    y_test_pred = model.predict(X_test)

    # Calculate metrics on Test
    acc = accuracy_score(y_test, y_test_pred)
    prec = precision_score(y_test, y_test_pred, average="binary")
    rec = recall_score(y_test, y_test_pred, average="binary")
    f1_test = f1_score(y_test, y_test_pred, average="binary")
    f1_train = f1_score(y_train, y_train_pred, average="binary")
    f1_val = f1_score(y_val, y_val_pred, average="binary")

    results[name] = {
        "Accuracy": acc,
        "Precision": prec,
        "Recall": rec,
        "F1-Score": f1_test,
        "F1-Train": f1_train,
        "F1-Val": f1_val,
        "model": model,
        "y_pred": y_test_pred
    }

    print(f"  Train F1:  {f1_train:.4f}")
    print(f"  Val F1:    {f1_val:.4f}")
    print(f"  Test F1:   {f1_test:.4f} (Accuracy: {acc:.4f})")
    print(f"  Precision: {prec:.4f} | Recall: {rec:.4f}")
    print(f"\n  Classification Report:")
    print(classification_report(y_test, y_test_pred, target_names=le.classes_))

print("\nAll models trained successfully!")

# 5. Model Comparison & Visualization
# 5.1 Confusion Matrices

# Plot confusion matrices for all models
fig, axes = plt.subplots(2, 2, figsize=(14, 12))

for idx, (name, res) in enumerate(results.items()):
    ax = axes[idx // 2, idx % 2]
    cm = confusion_matrix(y_test, res["y_pred"])
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", ax=ax,
                xticklabels=le.classes_, yticklabels=le.classes_,
                annot_kws={"size": 14})
    ax.set_title(f"Confusion Matrix \u2014 {name}", fontsize=13, fontweight="bold")
    ax.set_ylabel("Actual")
    ax.set_xlabel("Predicted")

plt.tight_layout()
plt.show()

"""### **5.2 Performance Comparison**

"""

# Create comparison dataframe
comparison_df = pd.DataFrame({
    name: {k: v for k, v in res.items() if k not in ["model", "y_pred"]}
    for name, res in results.items()
}).T

print("\nModel Performance Comparison:")
print(comparison_df.round(4).to_string())

"""### **5.3 ROC Curve**

"""

# 6. Cross-Validation (5-Fold)
# Cross-validation provides a more robust estimate of model performance by training and testing on different subsets of data.

# 5-Fold Stratified Cross-Validation
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
cv_results = {}

print("=" * 60)
print("5-FOLD CROSS-VALIDATION RESULTS")
print("=" * 60)

# Re-define models (fresh instances) with Pipeline
cv_models = {
    "Naive Bayes": Pipeline([("tfidf", get_tfidf()), ("clf", MultinomialNB())]),
    "SVM (LinearSVC)": Pipeline([("tfidf", get_tfidf()), ("clf", CalibratedClassifierCV(LinearSVC(random_state=42, max_iter=10000)))]),
    "Logistic Regression": Pipeline([("tfidf", get_tfidf()), ("clf", LogisticRegression(random_state=42, max_iter=1000))]),
    "Random Forest": Pipeline([("tfidf", get_tfidf()), ("clf", RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1))])
}

for name, model in cv_models.items():
    # Only run CV on X_train to prevent leakage
    scores = cross_val_score(model, X_train, y_train, cv=cv, scoring="f1")
    cv_results[name] = {
        "Mean F1": scores.mean(),
        "Std F1": scores.std(),
        "Scores": scores
    }
    print(f"\n{name}:")
    print(f"  F1 Scores per fold: {[f'{s:.4f}' for s in scores]}")
    print(f"  Mean F1: {scores.mean():.4f} (+/- {scores.std():.4f})")

# Visualize cross-validation results
fig, ax = plt.subplots(figsize=(10, 6))

names = list(cv_results.keys())
means = [cv_results[n]["Mean F1"] for n in names]
stds = [cv_results[n]["Std F1"] for n in names]

bars = ax.bar(names, means, yerr=stds, capsize=5,
              color=["#3498db", "#e74c3c", "#2ecc71", "#f39c12"],
              edgecolor="black")
ax.set_title("5-Fold Cross-Validation \u2014 Mean F1-Score", fontsize=14, fontweight="bold")
ax.set_ylabel("F1-Score")
ax.set_ylim(0.7, 1.02)
ax.tick_params(axis="x", rotation=10)

for bar, mean in zip(bars, means):
    ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.01,
            f"{mean:.4f}", ha="center", va="bottom", fontweight="bold")

plt.tight_layout()
plt.show()

# 7. Hyperparameter Tuning (GridSearchCV)
# We use GridSearchCV to find the optimal hyperparameters for our best-performing model.

# Determine best model from CV results
best_model_name = max(cv_results, key=lambda n: cv_results[n]["Mean F1"])
print(f"Best model from CV: {best_model_name}")
print(f"Mean F1: {cv_results[best_model_name]['Mean F1']:.4f}")

# Define hyperparameter grids for each model (using clf__ prefix for pipeline)
param_grids = {
    "Naive Bayes": {
        "clf__alpha": [0.01, 0.1, 0.5, 1.0, 2.0, 5.0, 10.0]
    },
    "SVM (LinearSVC)": {
        "clf__estimator__C": [0.01, 0.1, 1.0, 10.0],
        "clf__estimator__max_iter": [5000, 10000]
    },
    "Logistic Regression": {
        "clf__C": [0.01, 0.1, 1.0, 10.0, 100.0],
        "clf__solver": ["lbfgs", "liblinear"]
    },
    "Random Forest": {
        "clf__n_estimators": [50, 100, 200],
        "clf__max_depth": [None, 10, 20, 30],
        "clf__min_samples_split": [2, 5]
    }
}

# Fresh instance of the best model inside a Pipeline
best_model_instances = {
    "Naive Bayes": Pipeline([("tfidf", get_tfidf()), ("clf", MultinomialNB())]),
    "SVM (LinearSVC)": Pipeline([("tfidf", get_tfidf()), ("clf", CalibratedClassifierCV(LinearSVC(random_state=42)))]),
    "Logistic Regression": Pipeline([("tfidf", get_tfidf()), ("clf", LogisticRegression(random_state=42, max_iter=1000))]),
    "Random Forest": Pipeline([("tfidf", get_tfidf()), ("clf", RandomForestClassifier(random_state=42, n_jobs=-1))])
}

from sklearn.model_selection import PredefinedSplit
print(f"\n--- GridSearchCV for {best_model_name} ---")

# Combine Train and Validation sets perfectly without wasting Validation data
X_train_val = pd.concat([X_train, X_val])
y_train_val = pd.concat([y_train, y_val])

# Create PredefinedSplit where training samples are -1, validation samples are 0
test_fold = np.concatenate([np.full(len(X_train), -1), np.zeros(len(X_val))])
ps = PredefinedSplit(test_fold)

grid_search = GridSearchCV(
    estimator=best_model_instances[best_model_name],
    param_grid=param_grids[best_model_name],
    cv=ps,
    scoring="f1",
    n_jobs=-1,
    verbose=1,
    refit=False # We will manually refit on X_train ONLY so X_val remains purely for validation
)

# Fit on the combined dataset using the predefined split to validate on X_val
grid_search.fit(X_train_val, y_train_val)

print(f"\nBest Parameters: {grid_search.best_params_}")
print(f"Best Validation F1-Score: {grid_search.best_score_:.4f}")

# Manually refit the best model on X_train ONLY so X_val remains untouched by weights training
tuned_model = best_model_instances[best_model_name].set_params(**grid_search.best_params_)
tuned_model.fit(X_train, y_train)

# Evaluate tuned model on all sets to prove it doesn't overfit
y_pred_tuned_train = tuned_model.predict(X_train)
y_pred_tuned_val = tuned_model.predict(X_val)
y_pred_tuned_test = tuned_model.predict(X_test)

print("=" * 60)
print(f"TUNED {best_model_name.upper()} \u2014 FINAL RESULTS")
print("=" * 60)
print(f"Train F1-Score: {f1_score(y_train, y_pred_tuned_train):.4f}")
print(f"Val F1-Score:   {f1_score(y_val, y_pred_tuned_val):.4f}")
print(f"Test F1-Score:  {f1_score(y_test, y_pred_tuned_test):.4f}")
print("-" * 30)
print(f"Test Accuracy:  {accuracy_score(y_test, y_pred_tuned_test):.4f}")
print(f"Test Precision: {precision_score(y_test, y_pred_tuned_test):.4f}")
print(f"Test Recall:    {recall_score(y_test, y_pred_tuned_test):.4f}")
print(f"\nClassification Report (Test Set):")
print(classification_report(y_test, y_pred_tuned_test, target_names=le.classes_))

# Compare before vs after tuning
orig_f1 = results[best_model_name]["F1-Score"]
tuned_f1 = f1_score(y_test, y_pred_tuned_test)
print(f"Before tuning F1: {orig_f1:.4f}")
print(f"After tuning F1:  {tuned_f1:.4f}")
print(f"Improvement:      {(tuned_f1 - orig_f1):.4f}")

# 8. Save Best Model
# We save the best model and the TF-IDF vectorizer using joblib so they can be loaded later for the web application.

# Save the Full Pipeline 
os.makedirs("saved_models", exist_ok=True)

pipeline_path = "saved_models/spam_pipeline.pkl"
encoder_path = "saved_models/label_encoder.pkl"

# Save the unified pipeline and encoder
joblib.dump(tuned_model, pipeline_path, compress=3)
joblib.dump(le, encoder_path)

print(f"Pipeline saved to: {pipeline_path}")
print(f"Label encoder saved to: {encoder_path}")

# Verify file sizes
for path in [pipeline_path, encoder_path]:
    if os.path.exists(path):
        size_kb = os.path.getsize(path) / 1024
        print(f"   {path}: {size_kb:.1f} KB")

# 9. Prediction Interface
# Create a reusable function to predict whether a given text is spam or ham.

# Load saved pipeline (simulating deployment)
loaded_pipeline = joblib.load(pipeline_path)
loaded_encoder = joblib.load(encoder_path)

def predict_spam(text, pipeline=loaded_pipeline, encoder=loaded_encoder):
    """
    Predict whether a text message is Spam or Ham.

    Args:
        text (str): Input text message
        pipeline: Trained ML pipeline (TF-IDF + Classifier)
        encoder: Fitted label encoder

    Returns:
        dict: Prediction result with label and confidence
    """
    # Clean the text
    cleaned = clean_text(text)

    # Predict directly via pipeline without manually calling vectorizer
    prediction = pipeline.predict([cleaned])[0]
    label = encoder.inverse_transform([prediction])[0]

    # Confidence score
    if hasattr(pipeline, "predict_proba"):
        proba = pipeline.predict_proba([cleaned])[0]
        confidence = max(proba)
    else:
        confidence = None

    return {
        "text": text,
        "prediction": label,
        "confidence": f"{confidence:.2%}" if confidence else "N/A"
    }

print("Prediction function ready!")

# Test predictions with sample texts
sample_texts = [
    # 1. Spam disguised as a job offer reply
    "Re: Your application status. Following up on our previous conversation regarding the remote position. Please complete the final step of your onboarding here: bit.ly/fake-onboard. Welcome to the team!",

    # 2. Ham with a shortened link - legitimate tutorial share
    "Hey! I just found that Python tutorial you were looking for on this site. It's a bit of a weird link but trust me, it's safe: bit.ly/py-notes-2024. See you in class!",

    # 3. Spam - professional-tone phishing / credential theft
    "Dear Customer, an unusual login attempt from Russia was detected on your account. If this was not you, please secure your account immediately by verifying your identity: secure-verify-bank.com/login.",

    # 4. Ham - university system notification containing 'Urgent' and 'penalties'
    "Urgent: Your submission for COS30049 Assignment 1 is missing a file. Please re-upload to Canvas before 11:59 PM tonight to avoid penalties. Technical Support Team.",

    # 5. Spam - personalised crypto investment lure
    "I've been following your work and I think you have the right mindset for our private investment circle. We're seeing 300% returns on $SOL this week. No BS, just results. Join our Telegram: t.me/fake-crypto.",

    # 6. Ham - legitimate Microsoft OTP notification
    "Your Microsoft password reset code is: 882910. If you did not request this code, please ignore this message. Do not share this code with anyone for security reasons.",

    # 7. Spam - fake brand (Netflix) urgency trick
    "Netflix: Your payment was declined. As a gesture of goodwill for the inconvenience, we are offering you 3 months of free Premium. Claim your reward before the offer expires: netflix-gift.net/claim.",

    # 8. Ham - legitimate work email mentioning project cost overruns
    "The Myki system project documentation has been updated in the shared drive. Please check the 'Cost Overruns' section on page 45 and provide your feedback by EOD. Best, Project Lead.",

    # 9. Spam - academic ghostwriting service targeting students
    "Struggling with your Computing Technology project? Our experts can help you code your ReactJS frontend and Python backend starting at just $50. Satisfaction guaranteed or money back! Contact us: academic-help.com.",

    # 10. Ham - casual family text containing '$' and 'ASAP'
    "Mom said you're not answering your phone. Are we still on for the $100 grocery run today? Let me know ASAP or I'm going without you!"
]

print("=" * 70)
print("SPAM DETECTION \u2014 SAMPLE PREDICTIONS")
print("=" * 70)

for i, text in enumerate(sample_texts, 1):
    result = predict_spam(text)
    icon = "SPAM" if result["prediction"] == "spam" else "HAM"
    display_text = text[:80] + ("..." if len(text) > 80 else "")
    print(f"\n[Test Case {i}/10] [{icon}] (Confidence: {result['confidence']})")
    print(f"   \"{display_text}\"")

"""---
## **Step 10: Summary & Conclusions**

### **Key Findings:**

1. **Dataset**: ~50,000 emails labeled as spam or ham (Spam-50k.csv).
2. **Preprocessing**: Text cleaned with NLTK - lowercase, URL/email/number placeholders, punctuation filtering.
3. **Feature Extraction**: TF-IDF vectorization with unigrams and bigrams (max 10,000 features).
4. **ML Type 1 - Classification**: Naive Bayes, SVM, Logistic Regression, Random Forest trained and evaluated.
5. **ML Type 2 - Clustering** (spam_topic_clustering.py): K-Means (k=4) on spam-only data reveals
   latent campaign themes (Phishing, Financial Fraud, Ad Spam, Malware).
6. **Evaluation Metrics**: Accuracy, Precision, Recall, F1-Score reported for all models.
7. **Anti-Leakage**: PredefinedSplit in GridSearchCV ensures the validation set is never touched during training.
8. **Cross-Validation**: 5-fold CV on training data confirms robust generalization.
9. **Model Saved**: Best tuned pipeline exported as spam_pipeline.pkl for deployment.

### **Next Steps (Assignment 3 \u2014 Web Application):**
- Integrate the saved model into a **FastAPI** backend
- Build a **React/HTML** frontend for user interaction
- Add data visualization features to help users understand results
- Deploy the application for user testing

---
*TechNova Team COS30049 Computing Technology Innovation Project*

"""